import Head from "next/head";
import Image from "next/image";
import MainNavbar from "../components/Navbar";
import Navbar from "../components/Navbar";
import styles from "../styles/Home.module.css";
import "bootstrap/dist/css/bootstrap.min.css";
import Footer from "../components/Footer";
import SectionOne from "../components/SectionOne";
import SectionTwo from "../components/SectionTwo";
import SectionThree from "../components/Sectionthree";


export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <MainNavbar />
      <SectionOne />
      <SectionTwo />
      <SectionThree />  
      <Footer />
    </div>
  );
}
